### ISSUE TITLE
Trigger function when selecteditem is changed

### ISSUE THREAD

**Issue by ekapradityagk** [ralphshane/UIComboBox#3]
Hi, Thanks for the work, really love it.

as in my title above, i try to trigger a selector when selecteditem is changed, can you show me how?

regards

**Comment by ralphshane** [comment]
```
[box setOnItemSelected:^(NSString *selectedObject, NSInteger selectedIndex) {
    NSLog(@"%@ selectd and index is %d", selectedObject, selectedIndex);
}];
```
you can replace the NSLog(...) with a trigger function.

**Comment by ekapradityagk** [comment]
wow!! Thank you very much,, i didnt realize it when i commented that line
